# Generated by Django 5.1.5 on 2026-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
